steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/graphis/graphis:$COMMIT_SHA
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/graphis/graphis:$COMMIT_SHA
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - graphis
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/graphis/graphis:$COMMIT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars
      - VERTEX_AI_PROJECT=$PROJECT_ID,VERTEX_AI_LOCATION=${_REGION}
      - --min-instances
      - "0"
      - --max-instances
      - "6"
substitutions:
  _REGION: asia-south1
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/graphis/graphis:$COMMIT_SHA
